// Stages: availability and future bookings (the "upcoming" side of the demo).
// Slots are generated by each professional's own bulk tool; bookings are made by
// customers through the real checkout and the sandbox bank.
import { checkout, publicSlots, tehranDate, tehranDay, tehranHour } from '../lib/booking-flow.mjs';

const items = (d) => (Array.isArray(d) ? d : d?.items ?? d?.value ?? []);

export const availability = {
  name: 'availability',
  async run({ as, state, log }) {
    const from = tehranDate(1);
    const to = tehranDate(7);
    for (const [key, ids] of [['pro1', state.ids.pro1], ['pro2', state.ids.pro2], ['bizPractitioner', state.ids.practitioner]]) {
      const s = await as(key);
      const res = await s.post('/v1/me/availability/bulk', {
        weekdays: [0, 1, 2, 3, 4, 5, 6],
        timeStart: '10:00',
        timeEnd: '21:00',
        slotMinutes: 60,
        dateFrom: from,
        dateTo: to,
      });
      log(`${key}: bulk slots ${from}..${to} -> ${JSON.stringify(res.data).slice(0, 120)}`);
      const sample = await publicSlots(s, ids.providerId, Object.values(ids.serviceIds)[0]);
      log(`${key}: ${sample.length} bookable slots visible publicly`);
    }
  },
};

/** The first free public slot for a seller on a Tehran day at or after an hour. */
async function slotAt(session, ids, serviceKey, dayOffset, hour) {
  const day = tehranDate(dayOffset);
  const slots = await publicSlots(session, ids.providerId, ids.serviceIds[serviceKey]);
  const hit = slots.find((x) => tehranDay(x.startAt) === day && tehranHour(x.startAt) >= hour && (x.status ?? 'available') === 'available');
  if (!hit) throw new Error(`no free slot on ${day} from ${hour}:00`);
  return hit.id;
}

export const futureBookings = {
  name: 'future-bookings',
  async run({ as, state, log }) {
    const b = (state.ids.bookings ??= {});
    const run = async (name, customerKey, seller, serviceKey, dayOffset, hour, opts = {}) => {
      if (b[name]) return b[name];
      const customer = await as(customerKey);
      const slotId = await slotAt(customer, seller, serviceKey, dayOffset, hour);
      const r = await checkout(customer, { professionalId: seller.providerId, serviceId: seller.serviceIds[serviceKey], slotId, ...opts });
      b[name] = { ...r, customerKey, slotId };
      log(`${name}: booking ${r.bookingId?.slice(0, 8)} decision=${r.decision} callback=${r.callbackStatus ?? '-'} -> ${r.resultLocation ?? '(pending at gateway)'}`);
      return b[name];
    };

    const { pro1, pro2, practitioner } = state.ids;
    // Day offsets from Sunday 2026-09-27: 2 = Tue 29, 3 = Wed 30, 4 = Thu 1 Oct, 5 = Fri, 6 = Sat.
    await run('F1-paid-pro2', 'cust1', pro2, 'gel', 2, 10);
    await run('F2-paid-salon', 'cust2', practitioner, 'facial', 2, 12);
    await run('F3-payment-failed', 'cust3', pro2, 'mani', 3, 11, { decision: 'failure' });
    await run('F4-payment-cancelled', 'cust4', pro2, 'mani', 3, 14, { decision: 'cancel' });
    await run('F5-governed-paid-to-cancel-default', 'cust2', pro1, 'party', 4, 11, { governed: true });
    await run('F6-governed-paid-to-cancel-reschedule', 'cust3', pro1, 'party', 5, 11, { governed: true });
    await run('F7-governed-paid-customer-cancels', 'cust1', pro1, 'brow', 6, 12, { governed: true });
    await run('F8-paid-salon-upcoming', 'cust4', practitioner, 'color', 6, 15);
    await run('F9-governed-paid-upcoming', 'cust1', pro1, 'bridal', 3, 16, { governed: true });

    // Seller cancellations -> the customer's remedy (#161/#212).
    const pro1s = await as('pro1');
    for (const name of ['F5-governed-paid-to-cancel-default', 'F6-governed-paid-to-cancel-reschedule']) {
      if (b[name].sellerCancelled) continue;
      await pro1s.post(`/v1/bookings/${b[name].bookingId}/cancel`, { reason: 'بیماری ناگهانی متخصص (سناریوی دمو)' });
      b[name].sellerCancelled = true;
      log(`${name}: cancelled by the professional`);
    }
    // cust3 chooses a free reschedule instead of the default refund, if still offered.
    const c3 = await as('cust3');
    const remedy = await c3.get(`/v1/bookings/${b['F6-governed-paid-to-cancel-reschedule'].bookingId}/remedy`, { expect: [200, 404] });
    log(`F6 remedy view: ${JSON.stringify(remedy.data).slice(0, 200)}`);
    if (remedy.status === 200 && remedy.data?.rescheduleStillAvailable) {
      const newSlotId = await slotAt(c3, pro1, 'party', 6, 17);
      const chosen = await c3.post(`/v1/bookings/${b['F6-governed-paid-to-cancel-reschedule'].bookingId}/remedy`, { choice: 'reschedule', newSlotId });
      log(`F6 remedy chosen: ${JSON.stringify(chosen.data)}`);
    }
    // cust1 cancels well before the cutoff (free cancellation, full refund).
    const c1 = await as('cust1');
    if (!b['F7-governed-paid-customer-cancels'].customerCancelled) {
      await c1.post(`/v1/bookings/${b['F7-governed-paid-customer-cancels'].bookingId}/cancel`, { reason: 'تغییر برنامه (سناریوی دمو)' });
      b['F7-governed-paid-customer-cancels'].customerCancelled = true;
      log('F7: cancelled by the customer before the cutoff');
    }
  },
};
