<?php
declare( strict_types=1 );

namespace BeauClick\AI\Professional;

use BeauClick\Analytics\Metrics\MetricsService;
use BeauClick\Campaigns\CampaignService;
use BeauClick\Financial\LedgerService;
use BeauClick\Financial\SettlementService;

/**
 * The ONLY place that assembles data for a professional's AI conversation.
 * Every method here requires an already-resolved $provider_id — this class
 * never resolves ownership itself (that is
 * ProfessionalAssistantService::resolve_provider_id()'s job, backed by
 * ProviderLookup::for_user() against the current session) and never accepts
 * anything the client could influence. Task §15: "no arbitrary SQL
 * generated by the model... a controlled server-side context layer."
 *
 * Deliberately narrow for Phase 1 (task §11/§17/§18/§19's own instructions
 * to minimize PII and prefer aggregates over raw rows):
 *
 * - Booking/review/customer figures: MetricsService::for_provider() only —
 *   the same already-ownership-scoped counts the real Analytics tab shows.
 *   No customer names, emails, phones, or individual booking rows ever
 *   reach this context.
 * - Financial figures: SettlementService::party_summary()/
 *   outstanding_orders_for_party() only — the same authoritative source the
 *   real Revenue tab reads (Step 18). No second calculation engine.
 * - Campaign figures: CampaignService::all() filtered to this provider's own
 *   (or platform-wide) campaigns, with each one's real usage_summary() — no
 *   independent discount/eligibility calculation (Step 17 owns that).
 * - CRM notes and individual review text are deliberately EXCLUDED from
 *   Phase 1 (task §18/§19's own "if too sensitive, exclude — don't include
 *   just because the database makes it accessible" instruction). CRM notes
 *   are free-text, professional-authored, potentially containing customer
 *   PII, with no existing safe-summarization code (confirmed during this
 *   step's own architecture audit) — feeding them raw into a prompt would be
 *   new, unvetted PII/prompt-injection surface for a Phase 1 feature that
 *   does not need them: every question this phase promises to answer
 *   ("how are my bookings performing," "what's my top service," "what's my
 *   revenue") is already fully answered by the three aggregate sources
 *   above. The same reasoning excludes raw review body text — only the
 *   count/avgRating aggregate MetricsService already computes is used;
 *   review text is customer-generated, untrusted content (task §19) with no
 *   existing sentiment/theme aggregation to reuse.
 */
final class ProfessionalContext {

	public function __construct(
		private readonly MetricsService $metrics = new MetricsService(),
		private readonly SettlementService $settlements = new SettlementService(),
		private readonly CampaignService $campaigns = new CampaignService()
	) {
	}

	/**
	 * @return array<string, mixed>
	 */
	public function for_provider( int $provider_id, string $provider_post_type ): array {
		[ $from, $to ] = MetricsService::normalize_range( null, null );

		return [
			'providerId' => $provider_id,
			'postType'   => $provider_post_type,
			'range'      => [ 'from' => $from, 'to' => $to ],
			'analytics'  => $this->analytics_section( $provider_id, $provider_post_type, $from, $to ),
			'financial'  => $this->financial_section( $provider_post_type, $provider_id ),
			'campaigns'  => $this->campaigns_section( $provider_id ),
		];
	}

	/** @return array<string, mixed> */
	private function analytics_section( int $provider_id, string $provider_post_type, string $from, string $to ): array {
		return $this->metrics->for_provider( $provider_id, $provider_post_type, $from, $to );
	}

	/**
	 * Mirrors MyFinanceController's own party-type resolution exactly
	 * (owner-only, no staff fallback — Step 18's own standing "financial
	 * data stays owner-only" boundary, restated by this step's own task
	 * spec §12 as a requirement for AI too).
	 *
	 * @return array<string, mixed>|null Null for a post type with no
	 *         financial party mapping (should not happen given the caller
	 *         already resolved provider_id via ProviderLookup, but this
	 *         class never assumes — a missing mapping means "no financial
	 *         section," never a guess).
	 */
	private function financial_section( string $provider_post_type, int $provider_id ): ?array {
		$party_type = match ( $provider_post_type ) {
			'bc_business' => LedgerService::PARTY_BUSINESS,
			'bc_professional' => LedgerService::PARTY_PROFESSIONAL,
			default => null,
		};
		if ( null === $party_type ) {
			return null;
		}

		return [
			'summary'     => $this->settlements->party_summary( $party_type, $provider_id ),
			'outstanding' => $this->settlements->outstanding_orders_for_party( $party_type, $provider_id ),
		];
	}

	/**
	 * All campaigns whose targeting either includes this provider
	 * specifically or applies platform-wide (providerId === null) —
	 * matching CampaignService::active_candidates()'s own PHP-side filter
	 * shape (no `for_provider()` read method exists on CampaignService
	 * today; this mirrors the same pattern rather than adding one, since
	 * this is the only caller that needs it and the whole table is always
	 * small). Bounded to currently-active campaigns only — a draft/paused/
	 * archived campaign is not something a professional is currently
	 * running and would only confuse an AI narration of "what's live now."
	 *
	 * @return list<array<string, mixed>>
	 */
	private function campaigns_section( int $provider_id ): array {
		$active = array_values(
			array_filter(
				$this->campaigns->all(),
				static fn ( array $c ): bool => CampaignService::STATUS_ACTIVE === $c['status']
					&& ( null === $c['providerId'] || $provider_id === $c['providerId'] )
			)
		);

		return array_map(
			function ( array $c ): array {
				$usage = $this->campaigns->usage_summary( $c['id'] );
				return [
					'name'          => $c['name'],
					'discountType'  => $c['discountType'],
					'discountValue' => $c['discountValue'],
					'startsAt'      => $c['startsAt'],
					'endsAt'        => $c['endsAt'],
					'usageCount'    => $usage['count'],
					'totalDiscount' => $usage['totalDiscount'],
				];
			},
			$active
		);
	}
}
