module.exports = {
  displayName: 'api',
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  testMatch: ['<rootDir>/src/**/*.spec.ts', '<rootDir>/test/**/*.e2e-spec.ts'],
  transform: { '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.json' }] },
  moduleNameMapper: {
    '^@beauclick/http$': '<rootDir>/../../libs/http/src/index.ts',
    '^@beauclick/auth$': '<rootDir>/../../libs/auth/src/index.ts',
    '^@beauclick/ownership$': '<rootDir>/../../libs/ownership/src/index.ts',
    '^@beauclick/testing$': '<rootDir>/../../libs/testing/src/index.ts',
    '^@beauclick/identity$': '<rootDir>/../../services/identity/src/index.ts',
    '^@beauclick/provider$': '<rootDir>/../../services/provider/src/index.ts',
    '^@beauclick/money$': '<rootDir>/../../libs/money/src/index.ts',
    '^@beauclick/events$': '<rootDir>/../../libs/events/src/index.ts',
    '^@beauclick/booking$': '<rootDir>/../../services/booking/src/index.ts',
    '^@beauclick/commerce$': '<rootDir>/../../services/commerce/src/index.ts',
    '^@beauclick/payment$': '<rootDir>/../../services/payment/src/index.ts',
    '^@beauclick/financial$': '<rootDir>/../../services/financial/src/index.ts',
    '^@beauclick/search$': '<rootDir>/../../services/search/src/index.ts',
    '^@beauclick/notification$': '<rootDir>/../../services/notification/src/index.ts',
    '^@beauclick/media$': '<rootDir>/../../libs/media/src/index.ts',
    '^@beauclick/audit$': '<rootDir>/../../libs/audit/src/index.ts',
    '^@beauclick/subject-data$': '<rootDir>/../../libs/subject-data/src/index.ts',
    '^@beauclick/privacy$': '<rootDir>/../../services/privacy/src/index.ts',
  },
  testTimeout: 20000,
};
