module.exports = {
  displayName: 'api',
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  // `database/scripts` is workspace infrastructure rather than an Nx project
  // -- it has no package.json and is not a pnpm workspace member, so it cannot
  // carry its own runner without also carrying its own dependency tree. Its
  // pure logic is tested HERE instead, by the project that already has `pg`,
  // ts-jest, and a fast suite. The alternative was a script whose only
  // verification is that somebody ran it once.
  roots: ['<rootDir>', '<rootDir>/../../database'],
  testMatch: [
    '<rootDir>/src/**/*.spec.ts',
    '<rootDir>/test/**/*.e2e-spec.ts',
    '<rootDir>/../../database/scripts/**/*.spec.ts',
  ],
  transform: { '^.+\\.ts$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.json' }] },
  moduleNameMapper: {
    '^@beauclick/http$': '<rootDir>/../../libs/http/src/index.ts',
    '^@beauclick/auth$': '<rootDir>/../../libs/auth/src/index.ts',
    '^@beauclick/ownership$': '<rootDir>/../../libs/ownership/src/index.ts',
    '^@beauclick/testing$': '<rootDir>/../../libs/testing/src/index.ts',
    '^@beauclick/identity$': '<rootDir>/../../services/identity/src/index.ts',
    '^@beauclick/provider$': '<rootDir>/../../services/provider/src/index.ts',
    '^@beauclick/money$': '<rootDir>/../../libs/money/src/index.ts',
    '^@beauclick/events$': '<rootDir>/../../libs/events/src/index.ts',
    '^@beauclick/booking$': '<rootDir>/../../services/booking/src/index.ts',
    '^@beauclick/commerce$': '<rootDir>/../../services/commerce/src/index.ts',
    '^@beauclick/payment$': '<rootDir>/../../services/payment/src/index.ts',
    '^@beauclick/financial$': '<rootDir>/../../services/financial/src/index.ts',
    '^@beauclick/observability$': '<rootDir>/../../libs/observability/src/index.ts',
    '^@beauclick/search$': '<rootDir>/../../services/search/src/index.ts',
    '^@beauclick/notification$': '<rootDir>/../../services/notification/src/index.ts',
    '^@beauclick/media$': '<rootDir>/../../libs/media/src/index.ts',
    '^@beauclick/audit$': '<rootDir>/../../libs/audit/src/index.ts',
    '^@beauclick/subject-data$': '<rootDir>/../../libs/subject-data/src/index.ts',
    '^@beauclick/privacy$': '<rootDir>/../../services/privacy/src/index.ts',
    '^@beauclick/ai$': '<rootDir>/../../services/ai/src/index.ts',
    '^@beauclick/chat$': '<rootDir>/../../services/chat/src/index.ts',
    '^@beauclick/chat-contract$': '<rootDir>/../../packages/chat-contract/src/index.ts',
    '^@beauclick/wishlist$': '<rootDir>/../../services/wishlist/src/index.ts',
    '^@beauclick/wishlist-contract$': '<rootDir>/../../packages/wishlist-contract/src/index.ts',
    '^@beauclick/referral$': '<rootDir>/../../services/referral/src/index.ts',
    '^@beauclick/referral-contract$': '<rootDir>/../../packages/referral-contract/src/index.ts',
    '^@beauclick/ai-contract$': '<rootDir>/../../packages/ai-contract/src/index.ts',
    '^@beauclick/persian-utils$': '<rootDir>/../../packages/persian-utils/src/index.ts',
  },
  testTimeout: 20000,
};
